### ISSUE TITLE
Craft CodeForHawaii pitch

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/organization#101]
McKay will be giving a brief intro to CfH at the Wet Ware Wednesday event (http://www.eventbrite.com/e/wetware-wednesday-with-hawaiian-airlines-tickets-6593444169)

These opportunities come up enough it would that we need to have a consistent pitch to make sure we hit all the important messages:

* Open to everyone
* Especially civic-minded technologists
* Part of larger national/international movement
etc....

**Comment by mckaydavis** [comment]
Document lives here:
https://docs.google.com/document/d/1jhVTODgvP6BqdC9GGXepYrfx5ntum2elCcJapYYAHrA/edit?usp=sharing

**Comment by ryankanno** [comment]
For this pitch on Wednesday, don't forget to cover March 5th. :)

**Comment by mckaydavis** [comment]
v0.1 done @: 
http://pitch.cfh.link
