### ISSUE TITLE
Create 2016 Strategic Plan

### ISSUE THREAD

**Issue by ryankanno** [CodeforHawaii/organization#104]
As a participant in the Code for America network, we need to create a 2016 Strategic Plan to be an official Brigade.

**Comment by mckaydavis** [comment]
Strategic Plan 2016 Template from CfA copied to our drive at:
https://docs.google.com/a/codeforhawaii.org/document/d/1NWPYl8Wk9s7o9jL8hzr-NkCatXSaLXbM0Amd-VdgWq4/edit?usp=sharing

**Comment by ryankanno** [comment]
Emailed Monique for clarification about the template. Awaiting her response.

**Comment by ryankanno** [comment]
Monique responded. That is the appropriate template that @mckaydavis linked to above.
