### ISSUE TITLE
Send Reminders to Attendees

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/organization#115]
### Send Reminders to Attendees

Reminder email should include directions to event, what to bring, and wifi codes.

**Comment by ryankanno** [comment]
- Make sure to mention #112.
- Make sure to mention the following hashtags: #unz16, #opendataday, #codeacross

**Comment by mckaydavis** [comment]
Working on copy...

* encourage more topics 
* Parking info
* Wifi Info
* Remember to bring computers
* Detailed schedule
* Food info
