### ISSUE TITLE
Take Pictures and Tweet!

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/organization#116]
### Take pictures and tweet! 

Tweeting during your event and taking pictures will help document the event. This will come in handy when you blog about the event. It'll also let the community know what you're up to.

**Comment by mckaydavis** [comment]
Hash tags are: #opendataday, #CodeAcross, #unconferenz 
Be sure to thank @HNL_OED and @MayorKirkHNL for sponsorship

**Comment by ryankanno** [comment]
@kluschek Going to get you invited into the Code Across slack so that you can post the pictures and updates in a channel that will reach Code for America.

**Comment by mckaydavis** [comment]
After the panel at 10am, I have a task in the agenda to show a twitter feed on the main between 10am and 4pm on the main screen using this link:

https://twitterfall.com/?trend=@codeforhawaii%21%231f2224&trend=%23CodeAcross%21%23656d17&trend=%23opendataday%21%23322337&trend=%23unz16%21%23920400
