### ISSUE TITLE
Generate PNGs of new logos

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/organization#121]
Render the SVGs of the new logo (in https://drive.google.com/open?id=0B1pbQjrivMXBQzIwQzgwQlo4eEk) to pngs of various resolutions

**Comment by mckaydavis** [comment]
Waiting on @jongeyer to provide final SVG tweaks.

**Comment by jongeyer** [comment]
Replaced the two SVG's of the logo on the drive.

**Comment by mckaydavis** [comment]
New repository created for SVG logo assets:
https://github.com/codeforhawaii/logo

Contains a script (linux-only) that will render the svg assets to a bunch of pngs:
https://github.com/CodeforHawaii/logo/blob/master/bin/make-pngs.sh

Square and noborder png versions of various widths and colors pngs of the logo uploaded to the google drive:
https://drive.google.com/open?id=0B1pbQjrivMXBQzIwQzgwQlo4eEk

Marking as Done
