### ISSUE TITLE
Use updated logo

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/organization#122]
After #121 is finished, we need to update the logo where it is used. Locations include:
- [x] codeforhawaii.org
- [x] twitter 
- [x] facebook 
- [x] google plus community
- [x] google+ profile
- [x] meetup
- [x] github
- [x] newsletter templates
- [x] presentation templates
- [x] onboarding / waffle poster

**Comment by ryankanno** [comment]
I am using the 2048 charcoal colored logo.
