### ISSUE TITLE
Help Open Food Facts

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/organization#146]
For Open Data Day, Open Food Facts is launching "What's in my shampoo?" - http://whatsinmyshampoo.com , a project to open data (like ingredients) for shampoos from as many parts of the world as possible.

Remote participation is thus very welcome!

**Comment by teolemon** [comment]
we have direct links for the contribution apps at 
http://android.openfoodfacts.org
http://ios.openfoodfacts.org

and we need as much help as ever :-) Feel free to spread the world and use it in future hackathons.
