### ISSUE TITLE
Design a new Text Logo that is visually distinct from CfA logo

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/organization#21]
Our text logo should be visually distinct from the Code For America logo, it is currently too similar. See: https://docs.google.com/document/d/1LIUcCLwmn-SR6_X93TOMIoIJOhNXd0t_27TAIOofdIo/edit#

Resulting assets should be in vector format (SVG ideally)

The guideline says to use the Brigade Helmet logo: https://docs.google.com/file/d/0B7kCNBAFaNnCU1ZLMm1qMnZFSWc/edit

**Comment by mckaydavis** [comment]
Storing iterations in Google Drive: /Code.For.Hawaii/Graphics and Images/New Logo Iterations/:
https://drive.google.com/drive/u/1/folders/0B4v5RYLpNaz8RlREQXoyX3JWVVU

**Comment by mckaydavis** [comment]
Placed Sara's versions, @russtoku's version, and @mckaydavis's version to drive

**Comment by jongeyer** [comment]
Created a couple logo options shown on different backgrounds:
https://drive.google.com/open?id=0B3Y6_jRgAkGwWi1GVlpZMGljeGc

**Comment by mckaydavis** [comment]
Logo selected. Awesome work @jongeyer!

Assets located at: https://drive.google.com/open?id=0B1pbQjrivMXBQzIwQzgwQlo4eEk

**Comment by billymeinke** [comment]
Many thanks @jongeyer

On Thu, Feb 11, 2016 at 2:04 PM, McKay Davis <notifications@github.com>
wrote:

> Logo selected. Awesome work @jongeyer <https://github.com/jongeyer>!
>
> Assets located at:
> https://drive.google.com/open?id=0B1pbQjrivMXBQzIwQzgwQlo4eEk
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CodeforHawaii/organization/issues/21#issuecomment-183118754>
> .
>



-- 
Billy Meinke, MEd
@billymeinke <https://twitter.com/billymeinke> / Web
<http://billymeinke.github.io>
