### ISSUE TITLE
Fill out Honolulu here: http://us-city.census.okfn.org/

### ISSUE THREAD

**Issue by McKayDavis** [CodeforHawaii/organization#5]
https://trello.com/c/MIkpPqOO/38-fill-out-honolulu-here-http-us-city-census-okfn-org

I came across this the other day and we're pretty low in the ranking, but I'm pretty sure it's because we just haven't filled out the data. We just need to fill out the data.

**Comment by rbvea** [comment]
@ryankanno was any action taken on this?  maybe this would be a good open data day project?
