### ISSUE TITLE
Remove Trello links from blog, homepage, etc

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/organization#61]
Scrub Trello links from sites

**Comment by ryankanno** [comment]
Need to do the following:
- [X] blog
- [ ] homepage
- [ ] wiki

**Comment by ryankanno** [comment]
Homepage was fixed in https://github.com/CodeforHawaii/codeforhawaii.github.io/commit/021d4b8f1bd913aa3210f9b710547f9fb36e3eb6
