### ISSUE TITLE
Github 101 Workshop

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/organization#62]
Plan and organize an intro to Github

**Comment by billymeinke** [comment]
I have a draft outline created, and I could use your help! What resources have you seen that helped you learn git or github? Add to my list here: https://docs.google.com/document/d/17gfiWOypFeZO7-Bb8k8qoDc8xXjgBCJ0VYFc-pcBKpE/edit?usp=sharing

**Comment by mckaydavis** [comment]
@billymeinke Can we schedule this for a time slot at Unconferenz?

**Comment by mckaydavis** [comment]
Awesome job @billymeinke!  We should schedule another one!
