### ISSUE TITLE
Migrate Sigumnd Trello board to waffle

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/organization#64]
Migrate this trello board:
https://trello.com/b/3zEO5rKF/sigmund

To this github repo of issues:
github.com/codeforhawaii/uipa_org
waffle.io/codeforhawaii/uipa_org

**Comment by ryankanno** [comment]
I did most of this today; there's a few tasks that still need to be cleaned up.

**Comment by ryankanno** [comment]
Completed this today.

One note: Since the deployment scripts aren't public (yet), I took a screenshot of the issues to transfer them to the deployment repository.

https://trello.com/b/3zEO5rKF/sigmund
