### ISSUE TITLE
Determine venue for 1st half of March 5th

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/organization#65]
Unconferenz has The `Iolani Sullivan Center booked for 1:30-8:30pm.

We should try to book a classroom for the 8:00am-1:30pm timeframe to work on projects

**Comment by McKayDavis** [comment]
Craft and email to Allison Blankenship

**Comment by mckaydavis** [comment]
Allison @ `Iolani says that they are unable to accomidate because SAT testing will be held during the 8:00am-1:30pm timeframe

Possible alternatives include: Manoa Innovation Center, UH Classroom

**Comment by Bytemarks** [comment]
The Manoa Innovation Center might not be a bad idea. Has anyone talked to them about it? If not, I can make the ask.

**Comment by mckaydavis** [comment]
The Blaisdell Center Hawaii Suites are the venue for the entire day.
