### ISSUE TITLE
Email core team + HTDC to start coordination process

### ISSUE THREAD

**Issue by ryankanno** [CodeforHawaii/organization#68]
Ryan/Burt/McKay have spoken to HTDC in various capacities. Can we get one email to unify that voice with everyone cc'ed.

**Comment by McKayDavis** [comment]
@ryankanno sent email on Nov 20th to Len and Cindy to give heads up on Mar 4-5th dates.

**Comment by ryankanno** [comment]
We set December 10th as a tentative meeting date at MIC.
