### ISSUE TITLE
Conference Call w/ Andrew Hyder re: attendance tools

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/organization#73]
Attendance Improvements
Here are our hypothesis for why attendance is a super important data to track:
1. Fundraising
2. Identify new people, regulars, people who used to come
3. Pull stories, needs, and lessons from members
4. ??? What else would make you excited about this data?
How would you prioritize these?

How do you track attendance now?

We want consistency? What challenges are there to collecting attendance?

What are some other uses for this data? How can we package it for you?

**Comment by ryankanno** [comment]
We're going to backburner this one for now.
