### ISSUE TITLE
Aggregate history into a document

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/organization#77]
Create a spreadsheet that documents all past events, hackathons, websites, etc... that tie together the Code for Hawaii story

**Comment by mckaydavis** [comment]
I started history document here:
https://docs.google.com/document/d/143kmZIM7ydqqb8K6RAGWw1scHZZs8mvIXbderR9NRnk/edit

**Comment by kluschek** [comment]
Started feeding this information into a google sheet in the proper format/template to go into TimeMapper
https://docs.google.com/a/codeforhawaii.org/spreadsheets/d/1s96N3J2CWyqsuZ6MtZKNqR9wCJl-962hWqysmUA_jzA/edit?usp=sharing

**Comment by mckaydavis** [comment]
Moving to done.  Work being done in #92 now.
