### ISSUE TITLE
Update the CodeForAmerca Honolulu page

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/organization#87]
This page:
https://www.codeforamerica.org/governments/honolulu/

is out of date and should be updated

**Comment by mckaydavis** [comment]
Steps to take:
1) clone github.com/codeforamerica/codeforamerica.org
2) modify https://github.com/codeforamerica/codeforamerica.org/blob/master/governments/honolulu/index.html
3) create a pull request

**Comment by arnoldsandoval** [comment]
McKay, what exactly do you need updated?

**Comment by Bytemarks** [comment]
Is there a way to preview the modified code before committing it?

**Comment by rbvea** [comment]
@Bytemarks I think you'd need to run it locally...

**Comment by rbvea** [comment]
@mckaydavis @arnoldsandoval I'm assuming we'd need to update the hero and the contact info, along with our current active apps?
