### ISSUE TITLE
Post HDOT Traffic Data online

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/organization#90]
I got the CDs from Tyler Tsubota @ Bikeshare, now we need to host it online. Preferably on Azure.

**Comment by ryankanno** [comment]
Please see @ryankanno for Azure tools.

Also, what kind of license is attached to this data?

**Comment by mckaydavis** [comment]
Data converted to csv and posted on https://data.cfh.link/dataset/hawaii-traffic-counts (subject to change in the future)
