### ISSUE TITLE
Hookup Meetup.com events to Slack feed

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/organization#95]
The #feed-codeforhawaii channel should provide notifications all Meetup.com RSVPs, comments, and events (in near real-time)

Zapier will do this, but Zapier is not free
https://zapier.com/zapbook/zaps/4736/share-meetup-rsvps-via-slack-messages/

**Comment by sakamosa** [comment]
Hooked it up via an Email integration. Will leave this here until we're sure it will work well enough for our purposes.

**Comment by mckaydavis** [comment]
Works perfect. Thanks @sakamosa!
